Support more voices (#3)
jackkinsella/midi-to-part-mp3s pull request #8
Opened 2019-06-16 07:56 UTC by oli-ver

create_voices() function creates a voices list based on the parameters
The list contains the voice name, the tracks for this voice and the instrument
In add_solo_track_bundles now this voices list is used and not sung_parts

2019-06-16 08:01 UTC, oli-ver commented
@jackkinsella I have a working example of how we could support more voices. The solution allows to specify all kinds of voices and combinations, i. e.

SATB --> # should work with default settings
SSAATTBB --> --common-solo-tracks 0 --soprano 1 2 --alt 3 4 --tenor 5 6 --bass 7 8
SSAA -->  --common-solo-tracks 0 --soprano 1 2 --alt 3 4 --tenor --bass
TTBB --> --common-solo-tracks 0 --soprano --alt --tenor 1 2 --bass 3 4

Currently every voice gets a number, even if there is only 1 (so "soprano 1" for SATB). If that bothers us I could still edit the voices list, but I wanted to check with you first that this is the right approach.

2019-06-16 08:55 UTC, jackkinsella commented
This is gonna be somewhat dependent on the fix for #1 since I've introduced logic for the tempo map track. The good news is that, soon, I hope the code will be able to auto-detect whether it needs what used by called the "common-solo-track", which will clean up the API a lot.

2019-06-16 08:57 UTC, jackkinsella commented
As for the API you suggested:

SATB --> # should work with default settings

=> +1
SSAATTBB --> --common-solo-tracks 0 --soprano 1 2 --alt 3 4 --tenor 5 6 --bass 7 8

=> +1, that's exactly how I imagined it should be

SSAA --> --common-solo-tracks 0 --soprano 1 2 --alt 3 4 --tenor --bass
TTBB --> --common-solo-tracks 0 --soprano --alt --tenor 1 2 --bass 3 4

=> In these two cases, would it be possible to leave out the un-used tracks? E.g. SSAA would become `--soprano 1 2 --alt 3 4` instead of `--soprano 1 2 --alt 3 4 --tenor --bass`

2019-06-16 09:16 UTC, oli-ver commented
> => In these two cases, would it be possible to leave out the un-used tracks? E.g. SSAA would become `--soprano 1 2 --alt 3 4` instead of `--soprano 1 2 --alt 3 4 --tenor --bass`

Only if we remove the defaults for SATB in the argument parser. Right now we need to overwrite the SATB default settings for `--tenor` and `--bass`.

2019-06-16 10:04 UTC, jackkinsella commented
I see.

 How about this: Could we remove the defaults from the arguments parser, like you say, but then have some second order functionality that intelligently figures out what tracks map to what voices based on the minimal input given to the CLI?

2019-06-16 10:32 UTC, oli-ver commented
> I see.
> 
> How about this: Could we remove the defaults from the arguments parser, like you say, but then have some second order functionality that intelligently figures out what tracks map to what voices based on the minimal input given to the CLI?

Good idea, I just changed that. Is this how you meant that?

2019-06-16 19:05 UTC, jackkinsella requested changes
The functionality all looks good. The only thing I'll request before merging this PR is that you add at least one regression test of the new CLI usage e.g. `--soprano 1 2 --alto 3 4`. See the example test I added in `tests`.

The other thing, which we can discuss and do in a future separate PR, is cleaning up the names and refactoring into more structured types (e.g. Voice vs Part).

2019-06-18 06:02 UTC, oli-ver commented on midi-to-part-mp3s
> +  voices: List[List[str][int]] = []
Ok, nested lists are quite common in Python. But I am not sure if the type hint is correct this way. A list can always contain n elements. I will check.

2019-06-18 06:03 UTC, oli-ver commented on midi-to-part-mp3s
> +  voices: List[List[str][int]] = []
Ok, nested lists are quite common in Python. But I am not sure if the type hint is correct this way. A list can always contain n elements. I will check.

2019-06-18 06:05 UTC, oli-ver commented on midi-to-part-mp3s
> +  for sung_part in sung_parts:
voice_midi_track could be better: it's the configured track number for the voice

2019-06-18 06:05 UTC, oli-ver commented on midi-to-part-mp3s
> +  for sung_part in sung_parts:
voice_midi_track could be better: it's the configured track number for the voice

2019-06-18 06:23 UTC, oli-ver commented on midi-to-part-mp3s
> +    message: mido.Message
No but in VSCode it is used for code completion. I think if I don't input it typing "message." will not list methods and fields.

2019-06-19 20:31 UTC, oli-ver commented on midi-to-part-mp3s
> +  track_number:int
No, it's true. I am currently not using an autoformatter. Are you? Formatting the code with autopep8 changes pretty much everything. I will change that.

2019-06-19 20:32 UTC, oli-ver commented on midi-to-part-mp3s
> +  if part_name != 'accompaniment':
Yes, I think we could optimize that :)

2019-06-19 20:35 UTC, oli-ver commented on midi-to-part-mp3s
> +  for sung_part in sung_parts:
I used voice_midi_tracks because it's a list actually

2019-06-19 20:42 UTC, oli-ver commented on midi-to-part-mp3s
> +        voice = [sung_part + ' ' + str(i+1), tracks, instrument]
mmh you are right, we could perhaps just add the needed fields to the Parts class

2019-06-19 20:44 UTC, oli-ver commented on midi-to-part-mp3s
> +def add_solo_track_bundles(voices: list):
With the change that there is no `--common-solo-track` anymore this is now just the method to add accompaniment tracks. I will update the description and refactor the name to `add_accompaniment()`

2019-06-19 20:46 UTC, oli-ver commented on midi-to-part-mp3s
> +  defaults, i. e.:
I changed that

2019-06-19 21:20 UTC, oli-ver commented
> The functionality all looks good. The only thing I'll request before merging this PR is that you add at least one regression test of the new CLI usage e.g. `--soprano 1 2 --alto 3 4`. See the example test I added in `tests`.
> 
> The other thing, which we can discuss and do in a future separate PR, is cleaning up the names and refactoring into more structured types (e.g. Voice vs Part).

I worked on some of the review topics and wanted to create a test for the new feature. Before I was able to begin I noticed that the regression test you added fails on my branch:

```
AssertionError: Sequences differ: [11.310998, 10.867007, 10.867007, 10.867007] != [11.310998, 11.310998, 11.310998, 11.310998]

First differing element 1:
10.867007
11.310998

- [11.310998, 10.867007, 10.867007, 10.867007]
+ [11.310998, 11.310998, 11.310998, 11.310998]

----------------------------------------------------------------------
Ran 2 tests in 31.780s

FAILED (failures=1)
```

That's strange to me as I did not change anything about the way you are editing the tracks to fix the timing issues. I will have a deeper look in the next days.

2019-06-20 06:27 UTC, oli-ver commented
Found it! This shows your regression test works very well :) I did not include the tempo map in the voices. I will work on the regression test now to make sure the files are created correctly, so i.e. if `--soprano 1 2` has been configured no other voices should be created, the default settings create default SATB and so on.

2019-06-20 08:57 UTC, oli-ver commented
During working on the unittest I stumbled across some issues with the file name. I wanted to import the module and call it's main method rather than calling it from the shell like you did. Therefore I had to change the filename on the way and change the application initilization a little bit. I also added a convenience script with the old name.

The changes will allow us to call separate methods of the script in future unit tests. Right now we both only developed end-to-end / integration tests, but this will probably change at some point i.e. if we only want to unittest a single method

2019-06-20 09:07 UTC, oli-ver commented on midi-to-part-mp3s
> +  voices: List[List[str][int]] = []
I changed that to List[List] to show that's a nested list. I don't think the previous way was even possible, I did not find it anywhere in the docs.

2019-06-21 13:21 UTC, jackkinsella approved these changes
Excellent stuff and just in time — I need to convert a SATTB track today.

Abendlied is a lovely choral piece. Our test fixtures have been thoughtfully curated :)

2019-06-21 13:21 UTC, jackkinsella commented on midi_to_part_mp3s.py
> +args = None
Thanks, big improvement in cleaner method sigs!

2019-06-21 13:22 UTC, merged